# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Veer < Formula
  desc "A live-diffing TUI for coding with AI"
  homepage "https://github.com/broothie/veer"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/broothie/veer/releases/download/v0.1.0/veer_0.1.0_darwin_amd64.tar.gz"
      sha256 "e5111e548e5a18626df61b163c7707ec5be1a69dde1a20e61d1457a47c80b45c"

      define_method(:install) do
        bin.install "veer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/broothie/veer/releases/download/v0.1.0/veer_0.1.0_darwin_arm64.tar.gz"
      sha256 "918499706b6a5199c98cd769acea44137af94cf5e01dcff0b90f837b61816e14"

      define_method(:install) do
        bin.install "veer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/broothie/veer/releases/download/v0.1.0/veer_0.1.0_linux_amd64.tar.gz"
      sha256 "861eebe4a7a4aea4a5fa2674f6485adfa73e96f6ad76a170fbe5490194320f0c"
      define_method(:install) do
        bin.install "veer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/broothie/veer/releases/download/v0.1.0/veer_0.1.0_linux_arm64.tar.gz"
      sha256 "443ac81d7786e9c45dc19971eabff0176f32613ec060ce33d14faf9630fa7afd"
      define_method(:install) do
        bin.install "veer"
      end
    end
  end
end
